server:
  port: 8084
spring:
  application:
    name: ms-divisiones

  datasource:
    url: jdbc:h2:mem:div_db
    driverClassName: org.h2.Driver
    username: sa
    password:

  spring:
    application:
      name: ms-divisiones

    datasource:
      url: jdbc:postgresql://${DB_HOST:${POSTGRES_HOST:localhost}}:${DB_PORT:5432}/${DB_NAME:asesoriasdb}
      username: ${DB_USER:divisiones}
      password: ${DB_PASSWORD:divisiones_pass}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
        connection-timeout: 30000

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate.default_schema: divisiones
        hibernate.jdbc.time_zone: UTC

    main:
      allow-bean-definition-overriding: true


